name: 🚀 Deploy Azure Function

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip deployment package
        run: zip -r function.zip .

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: pocfuncapp776561801
          package: ./function.zip
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
